version: 1

formatters:
  simple:
    format: "%(asctime)s %(name)s: %(message)s"
  extended:
    format: "%(asctime)s %(levelname)8s: %(name)s - %(message)s"

handlers:
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    filename: /etc/logs/actors.log
    formatter: extended

root:
  handlers: [file_handler]
  level: DEBUG
